### PR TITLE
Fixes #894. Default options are extracted from Atom Editor options

### LINKED ISSUE #894: Editor options of atom are ignored
### Description

It seems, that atom-beautify is using it's own default options (since the better-settings change) and not atom's editor settings.

I'm not using a .jsbeautifyrc nor a .editorconfig
### Expected Results

The beautified code should have looked like:

```
function Test() {
  var a,
    b,
    c;
}

```
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/grma1/1ca0b62883e4294c333642e831762f48
#### How to create `debug.md` Gist

Note that this will include a copy of your code.
If your code is private, please create a different sample of code that reproduces the problem.
1. In the Atom [command-palette](https://atom.io/packages/command-palette), 
   search for and run the command `Atom Beautify: Help Debug Editor`. 
   The debugging results will be copied to your clipboard.  
2. Create a new Gist at https://gist.github.com/  
3. Create a file in your new Gist called `debug.md`.  
4. Paste your debugging results from Atom beautify into `debug.md` file in your Gist.  
5. Add a link to your Gist in your new Issue.
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

### PR DESCRIPTION
**Pull request by Glavin001**
### What does this implement/fix? Explain your changes.

...

### Does this close any currently open issues?

...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch
- [ ] Added examples for testing to [examples/ directory](examples/)
- [ ] Travis CI passes (Mac support)
- [ ] AppVeyor passes (Windows support)

### CODE REVIEW

File: src/config.coffee [hunk 1]
```diff
@@ -6,6 +6,15 @@ module.exports = {
     order: -1
     description: 'General options for Atom Beautify'
     properties:
+      test1:
```
Comment (Glavin001) [inline src/config.coffee]: Remove these.

**Comment by Glavin001** [comment]
Published to v0.29.21.
